version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: corefans-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-setup:
    image: minio/mc
    container_name: corefans-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      /bin/sh -c "
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin} && \
        mc mb -p local/${MINIO_BUCKET_VIDEOS:-videos} || true && \
        mc mb -p local/${MINIO_BUCKET_THUMBS:-thumbs} || true && \
        mc anonymous set download local/${MINIO_BUCKET_THUMBS:-thumbs} || true && \
        echo 'Buckets ensured.' && sleep 3
      "
    restart: "no"

volumes:
  minio-data:
